project:
  type: website
  output-dir: _build
  pre-render: build_node_docs.py

filters:
  - preview-colour

website:
  title: "Molecular Nodes"
  sidebar:
    collapse-level: 1
    style: docked
    search: true
    contents:
      - href: index.md
        text: About
      
      - installation.md
      - panel.qmd
      - section: Tutorials
        contents: tutorials/*
      - examples.md
      - nodes.qmd
      # - section: API Reference
      #   contents: reference/*
    tools:
      - icon: github
        href: https://github.com/BradyAJohnston/MolecularNodes
      - icon: twitter
        href: https://twitter.com/bradyajohnston
      - icon: youtube
        href: https://youtube.com/c/bradyjohnston
  page-footer:
    left: "This site is built with ❤️ and [Quarto](https://quarto.org/)."
    background: "#F8F9FA"

format:
  html:
    page-layout: full
    grid: 
      sidebar-width: 250px
      body-width: 1000px
    theme: 
      light: yeti
      dark: superhero
    css: styles.css
    toc: true
    toc-depth: 2
    preview-colour:
      code: true
      text: true

# # generate python API docs
# quartodoc:
#   package: molecularnodes
#   # source_dir: ../molecularnodes
#   dir: reference
#   sections:
#     - title: Importing Files
#       desc: "Importing different data formats."
#       contents:
#         - name: io.pdb.load
#         - name: io.local.load
#         - name: io.cellpack.load
#         - name: io.star.load



